exports.types = {
	"txt" : "text/plain",
	"html": "text/html",
	"xml" : "text/xml",
	"css" : "text/css",
	"js"  : "text/javascript",
	"gif" : "image/gif",
	"ico" : "image/x-icon",
	"jpeg": "image/jpeg",
	"jpg" : "image/jpeg",
	"png" : "image/png",
	"svg" : "image/svg+xml",
	"tiff": "image/tiff",
	"json": "application/json",
	"pdf" : "application/pdf",
	"swf" : "application/x-shockwave-flash",
	"wav" : "audio/x-wav",
	"wma" : "audio/x-ms-wma",
	"wmv" : "video/x-ms-wmv",
};